name: first_task
on: push
jobs:
    check-out:
        runs-on: ubuntu-latest
        steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Lint Code
          run: npm run lint
        - name: Test Code
          run: npm run test
        - name: Build Code
          run: npm run build
    deploy:
        runs-on: ubuntu-latest
        needs: check-out
        steps:
         - name: Deploy
           run: echo "Deploying Code"